baseURL = "https://hololena.github.io/MeMyselfAndMyAvatars"
languageCode = "de"
title = "Me, Myself & My Avatars"
theme = ["hugo-shortcode-gallery", "avatars"]
canonifyurls = true

[menu]
[[menu.main]]
name = "Team"
url = "/team/"

[[menu.main]]
name = "Projekt"
url = "/"

[Author]
name = "Lena Biresch"
email = "mailto:lena.biresch@gmx.de"

[Params]
titel = "Me, Myself & My Avatars"
favicon = "/MeMyselfAndMyAvatars/img/Avatar_Icon.png"

[markup.goldmark.renderer]
unsafe= true
